//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_RATING
    {
        public string EmployeeName { get; set; }
        public string SAP_Module { get; set; }
        public Nullable<int> Basic_Operation { get; set; }
        public Nullable<int> Priority_Daily_Work { get; set; }
        public Nullable<int> Document_Resource { get; set; }
        public Nullable<int> SAP_Environment { get; set; }
        public Nullable<int> Dept_Colleagues_SAP_ERP { get; set; }
        public Nullable<int> Line_Manager_SAP_ERP { get; set; }
        public Nullable<double> Overall_Rating { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string SAP_Question1 { get; set; }
        public string SAP_Question2 { get; set; }
        public string SAP_Question3 { get; set; }
        public string SAP_Question4 { get; set; }
        public string SAP_Question5 { get; set; }
        public string SAP_Idea1 { get; set; }
        public string SAP_Idea2 { get; set; }
        public string SAP_Idea3 { get; set; }
        public string SAP_Idea4 { get; set; }
        public string SAP_Idea5 { get; set; }
        public int EmployeeID { get; set; }
    }
}
